# WARNING! This file is not managed by Ansible and should not contain any usage of its features.
---
tmproot: /tmp
webroot: /var/www
project: cikit-rest-api
site_url: https://cikit-rest-api.loc
vm:
  ports: [1337]
  folders:
    - source: ./docroot
      target: /var/www/cikit-rest-api
